version: "3.8"

services:
  client:
    build:
      context: ./client
    ports:
      - "4200:4200"
    container_name: client
    depends_on:
      - api
      - webapi

  api:
    build:
      context: ./nodeapi
    ports:
      - "5000:5000"
    restart: always
    container_name: api
    environment:
      MONGO_URL: mongodb://emongo:27017/emart   # FIXED
    depends_on:
      - emongo

  webapi:
    build:
      context: ./javaapi
    ports:
      - "9000:9000"
    restart: always
    container_name: webapi
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://emartdb:3306/emart?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpass
    depends_on:
      - emartdb

  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"

  emongo:
    image: mongo:4
    container_name: emongo
    environment:
      MONGO_INITDB_DATABASE: emart    # FIXED
    ports:
      - "27017:27017"

  emartdb:
    image: mysql:5.7             # FIXED: use compatible version
    container_name: emartdb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass   # must match WebAPI
      MYSQL_DATABASE: emart           # FIXED DB name
    ports:
      - "3306:3306"

volumes:
  mongo_data:
  mysql_data:
